import React from "react";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "aos/dist/aos.css";
import type { Metadata } from "next";
import { Nunito_Sans, Kristi } from "next/font/google";
import WithAOS from "@/components/withoas/WithAOS";
import Header from "@/components/header/Header";
const Footer = React.lazy(() => import("@/components/footer/Footer"));

// Load Nunito Sans font
const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["1000", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});
// Load Kristi font
const kristi = Kristi({
  subsets: ["latin"],
  weight: ["400"], // Kristi supports only 400 weight
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "BLING wedding",
  icons: "/logo.webp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.className} ${kristi.className}`}>
      <head>
        {/* <link
          rel="preload"
          as="image"
          href="/_next/image?url=%2F14.webp&w=345&q=75"
        /> */}
        {/* Preload critical JS chunks */}
        <link
          rel="preload"
          href="/_next/static/chunks/1517-111b6675d80f7ce9.js"
          as="script"
        />
        <link
          rel="preload"
          href="/_next/static/chunks/4bd1b696-84a26fccac2fd0d4.js"
          as="script"
        />
        <link rel="preload" href="/1.mp4" as="video" />
        <link rel="preload" href="/4.mp4" as="video" />
        <link rel="preload" href="/8.mp4" as="video" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <WithAOS>
          <Header />
          {children}
          <Footer />
        </WithAOS>
      </body>
    </html>
  );
}
